### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by jorgebodega** [jorgebodega/typeorm-seeding#48]
Version 3 has been released, with a lot of breaking changes so please be sure you can use it.

Version 3 (latest):
```
yarn add [-D] @jorgebodega/typeorm-seeding
```

Version 2 (previous):
```
yarn add [-D] @jorgebodega/typeorm-seeding@2
```

Bundle size has been decreased a lot:

[345kB](https://bundlephobia.com/package/typeorm-seeding@1.6.1) vs [3.5kB](https://bundlephobia.com/package/@jorgebodega/typeorm-seeding@3.0.0)

**Comment by adrien-may** [comment]
Hi there, I haven't had the time to test latest version yet. Again, thanks for the energy you're putting in this library, I really appreciate it. I'm more confortable with the latest choices you made in this release with the use of `class MyModelFactory extends Factory<MyModel>`, it's closer to what I've been used to in factory boy (python implementation)

In the newest README, I did not see any mention of "context". It was a neat way to give extra info to the factory to get specific outcomes from it. I did not see the code in details yet but 2 possibilities : 

- you removed this feature (if so, do you plan to put it back ? Do you need help doing so ? Or do you think it was a bad idea to begin with?)
- you forgot to add it in the doc (if so, do you need help to write it ?)

Cheers !

Bundle size is smaller... but faker is no more included, so the library does """less""".
Maybe we could start documentation or examples with:
- [fakerjs](https://github.com/MilosPaunovic/community-faker) from the community edition obviously
- [chance](https://chancejs.com/)
- etc...

I'd be happy to help or submit PR if you provide some guidance over your plans for this library.

**Comment by jorgebodega** [comment]
Hi!

Yes, I removed that feature, I see there is no need to have it since there are some other ways to override values and there could be more than one factory per entity. If you think it should be there, please explain your point, will be great to read it.

And yes, I removed faker as a dependency, because there is no need to have it, this library could be used even if is not installed. But of course, I have plans to add some extense examples with TypeORM entities, factories, seeders, faker... in the next weeks.

In this moment, I don't have any more plans, just see if some more people could bring some feedback like yours

EDIT: I forgot, not 100% comfortable on how seed command works, now and before, so if you have any idea on how to improve it, please share it

**Comment by adrien-may** [comment]
For now, I'm not using the seed part, only the factories. I discovered this project 2 weeks ago...  But I was not expecting so much of a hassle haha (the fork, fakerjs being removed from the author and v3 release...)
It's quite unstable right now :/

I can't find any good example where the "context" I was using cannot be replaced with several Factories... But requiring a lot of factories could be a pain.

Let say we have a model A with field a1, a2, b3, b4, a11, a12, a21, a22, b31, b32, b41, b42
This model is made so that if you have a value in a1, a2 would be null and if you got a value for a2, a1 is null
If a1 has a value, you get value for a21 and a22 etc etc
Same kind of rules applies for b3 and b4.

With an object passed to the factory, you could give something like { a: 1, b: 4 }
and the factory will be able to make an object with a value in a1 but not a2, a value in b4 but not b3 and the related a11, a12, b41, b42.

The point is: if we try to create as many factories as composition we could get, it's getting out of hands. With this example, we would need 4 factories.
We could argue that one can have a few factories and then correct them with the fields being overridden when needed.
Or we could say that this "A" model is absurd and probably badly designed. 😂  I tried to come with an example but I'm not sure I'm proving a point here...

I had a second look to the README, I think an example of a factory being called within another factory is a must have to demonstrate what this lib can achieved even if it can seem obvious.

I'll give a try to this version tomorrow, I'll let you know if I encounter any problems or if I have any proposal to make.

**Comment by jorgebodega** [comment]
Ok, I'll wait then.

I used the original library every day at work, but is unmaintained, and I cannot do anything because the owner does not give me the token to deploy.

I will work on this since is core in my project, for testing and seeding

**Comment by adrien-may** [comment]
Hi there, some questions/suggestions for you:

- Do we need to create new instances of factories every time before calling create, make etc ? I'm not sure what the benefits are.
Could we instead directly call `UserFactory.create()` or `UserFactory.make()` instead of `new UserFactory().create()` ? I feel the constructor is not adding much value but I may be plain wrong.

- Feature suggestion: Add a sequence generator? (maybe via adding a counter on the factory class) Let's say you want all your instances of a model to have something like `firstName = "John n°XX"`where XX is an auto incremental integer. It could be neat.

- We may have a performance gain if we rewrite `createMany` so that we take advantage of the async await part ? With a Promise.all() for example instead of waiting at each save before creating the next one ?

Last thing I'm thinking, let's say our factory calls a lot of subfactories and I decide to override values when calling the factory.
makeEntity will first use all the subfactories from the definition function and then (eventually) call again the same factories to override it. Maybe if fields are overriden, they should not be computed in the definition function in the first place.
If we really want to go further, we could imagine that a factory takes an Entity in its constructor or as a static field and makes some introspection on the entity class to automagically generate entity with the help of faker, chance, whatever. That's more what I'm looking for. At the end, if we only make use of factories where we create a new entity, define all the value "by hand" and eventually override some values, we create almost no value. If we're able to use typeorm entities correctly (and typing!!), we could get factories in no time, and only add specific faker functions where we want more fuzziness. What do you think?

What feels strange right now is that a Factory does not depend on the entity it is building (types set apart). It might lead to unexpected behavior and a bad developper experience. What are your thoughts on this?

**Comment by jorgebodega** [comment]
Hi!

- I don't think using static methods here could be a good idea. Is not possible to use abstract with static functions, and definition method could not be overrided. For me, that part of the application should stay like that. Also, it is possible to use like [this test](https://github.com/jorgebodega/typeorm-seeding/blob/374d1d2812bc02e49695586c58d9c44398a21b79/test/factory.test.ts#L10)
- For me, it makes no sense to have that type of functionality. I clearly prefer to maintain sequences and that type of stuff on TypeORM, this library does not pretend to override ORM functionality
- Yes, this could be possible, but I strongly believe using concurrency here could led to some errors while creating big amount of stuff.

About the big paragraph, I do not understand very well, could you give an example?

And last but not least, I think factory typing is very good here, it is agnostic of entities and is client responsability to correctly check that entity is pointing the desired class

**Comment by adrien-may** [comment]
I just found https://github.com/linnify/typeorm-factory and most of the features I wanted are implemented there. I think I'll give it a try, I'll let you know if I end up using your fork.

**Comment by jorgebodega** [comment]
I read that library, seems great!

I'll still maintain this because I use it everyday and prefer the simplicity, but if you're not using seeding and prefer that library, would be great if you come back after some time and share your opinions!

**Comment by adrien-may** [comment]
Obviously, my plan is not to make you use another library. Yours is great too and I'd be happy to help if you need. typeorm-factory is closer to my needs but it has some flaws. I'm gonna try it today and if it's not up to my needs, I'll write some PRs or my own version unless I find another flavor of this factory implementation 🤷🏻  I'll let you know !

**Comment by adrien-may** [comment]
I ended up writing my own. I plan to extend it to be typeorm agnostic and also work with other ORM I use. This is a WIP but you can have a look [here](https://github.com/teamMay/factory) if you want  (a lot more work is needed), I still need to battle test it in real production envs. I'm working on it this week. Cheers ! (and congrats on the latest release)
