### ISSUE TITLE
Allow async .map functions

### ISSUE THREAD

**Issue by jsouto18** [jorgebodega/typeorm-seeding#76]
Hey! 
I've been using this library recently and I've noticed that using async map functions are not currently allowed. This would be a nice Quality of Life feature to have on the library!

**Comment by jsouto18** [comment]
@jorgebodega you mentioned that the .map function is going away. Is there a reason for that breaking change?

**Comment by jorgebodega** [comment]
I'm trying to move the library to something similar to [MikroORM](https://mikro-orm.io/docs/seeding#entity-factories) and [Factory](https://github.com/teamMay/factory), and I do not see why is necessary to maintain that functionality.

If you think I should retain that, pls tell me your use case

**Comment by jsouto18** [comment]
Example below. Also is there a way to use `make` instead of `create` for relation entities?
Example:
```
export class EstablishmentSeeder extends Seeder {
  async run() {
    await new EstablishmentFactory().createMany(4);
    await new EstablishmentFactory()
      .map(async (ele) => {
        ele.entity = await new EntityFactory().create({
          entityType: "PRE",
        });
      })
      .create();
  }
}
```

**Comment by jorgebodega** [comment]
Oh, now I see. Yes, that approach is interesting, because that function is executed once per entity. That functionality should be covered on https://github.com/jorgebodega/typeorm-seeding/pull/79 with function support on attributes. Could you take a look?

And now there is no other way than just `create` or `make`. If you don't have cascade option enabled for that entity, `create` must be called. Really don't like that, but checking entity metadata for cascade option are completely out-of-scope

**Comment by jsouto18** [comment]
Yes it is covered by #79! Thanks I think we can close this issue 👍🏼
